Add opentitan_synth target with patches
antmicro/yosys-uhdm-plugin-integration pull request #1594
Opened 2023-03-21 13:37 UTC by kamilrakoczy

This PR adds opentitan_synth target and patches to make it build.

2023-03-22 15:10 UTC, mglb requested changes
Other than some naming and paths it looks OK.

2023-03-22 15:10 UTC, mglb commented on uhdm-tests/opentitan/Makefile.in
> +                        && git apply ${curr_dir}/0018-Fix-some-out-of-range-access.patch \
Please create a directory for those patches. Otherwise we'll have patches for 3 tests and 3 repos in a single directory.

2023-03-22 15:10 UTC, mglb commented on uhdm-tests/opentitan/Makefile.in
> +${OPENTITAN}/.gitpatch_tiny:
`.gitpatch_synth`

2023-03-23 17:08 UTC, wsipak requested changes

2023-03-27 07:02 UTC, kamilrakoczy commented on uhdm-tests/opentitan/Makefile.in
> +                        && git apply ${curr_dir}/0001-Fix-Failed-to-detect-width-for-parameter.patch \
As we are using different patches for the same repository, creating commits from patches makes local development a bit harder to maintain. We would need to reset history to original point (that is in git repo) before trying to apply patches.

But I don't have hard opinion on this, if others also think ``git am`` is better, I can change this.

2023-03-27 10:12 UTC, wsipak commented on uhdm-tests/opentitan/Makefile.in
> +                        && git apply ${curr_dir}/0001-Fix-Failed-to-detect-width-for-parameter.patch \
Alright!

2023-03-28 13:45 UTC, wsipak approved these changes

2023-03-28 13:47 UTC, merged