Add initial version of README
antmicro/yosys-uhdm-plugin-integration pull request #209
Opened 2021-11-26 13:53 UTC by kamilrakoczy

Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

2021-11-26 14:13 UTC, rkapuscik requested changes

2021-11-26 14:13 UTC, rkapuscik commented on README.rst
> +#. Order of the files in Surelog command matters. Surelog requires that all definitions needs to be already defined, when file is parsed (if file ``B`` is defining type used in file ``A``, file ``B``
Typo in the last sentence: 
`Surelog requires that all definitions needs to be already defined, when file is parsed` -> `Surelog requires that all definitions need to be already defined when file is parsed`.

(also, that's true in general for Verilog and is not Surelog-specific).

2021-11-29 07:06 UTC, kamilrakoczy commented on README.rst
> +#. Order of the files in Surelog command matters. Surelog requires that all definitions needs to be already defined, when file is parsed (if file ``B`` is defining type used in file ``A``, file ``B``
Fixed.

2021-11-29 07:29 UTC, rkapuscik approved these changes

2021-11-29 13:16 UTC, merged